set scrolloff=8
set number
set relativenumber

set tabstop=2
set softtabstop=2
set shiftwidth=2
set expandtab
set smartindent

let mapleader=" "

inoremap jk <Esc>

nnoremap <leader><CR> :source ~/.config/vim/vimrc<CR>