#!/usr/bin/env bash

install_script_dir="$HOME/ms"

"$install_script_dir/machine-setup" d
"$install_script_dir/machine-setup" i
"$install_script_dir/machine-setup" c
if [ -n "$HYPRLAND_INSTANCE_SIGNATURE" ]; then
  hyprctl dispatch exit
fi