#!/usr/bin/env bash

XDG_DATA_HOME="${XDG_DATA_HOME:-$HOME/.local/share}"
target_dir="$XDG_DATA_HOME/machine-setup/path-scripts"

"$target_dir/machine-setup" d && "$target_dir/machine-setup" i && "$target_dir/machine-setup" c && hyprctl dispatch exit