#!/usr/bin/env bash

XDG_CONFIG_HOME="${XDG_CONFIG_HOME:-$HOME/.config}"

script_dir=$(cd $(dirname "${BASH_SOURCE[0]}") && pwd)
dry="0"

while [[ $# -gt 0 ]]; do
  if [[ $1 == "--dry" ]]; then
    dry="1"
  fi
  shift
done

clean_path() {
  first=$(echo "$1" | sed 's|/\./|/|g')
  shift
  echo "$first $@"
}

log () {
  if [[ "$dry" == "1" ]]; then
    echo "[DRY_RUN]: $(clean_path "$@")"
  else
    echo "$(clean_path "$@")"
  fi
}

execute() {
  log "execute $(clean_path "$@")"
  # if not dry
  if [[ "$dry" != "1" ]]; then
    "$@"
  fi
}

log "---------- Copy Config Scripts ----------"

copy_items() {
  from="$1"
  to="$2"

  if [[ ! -d "$from" ]]; then
    log "Source directory $from does not exist. Skipping."
    return
  fi

  pushd $from > /dev/null
  items=$(find . -mindepth 1 -maxdepth 1)
  popd > /dev/null

  for item in $items; do
    execute rm -rf $to/$item
    execute cp -r $from/$item $to/$item
  done
}

root_dir=$(dirname $(dirname $script_dir))

mkdir -p "$XDG_CONFIG_HOME"

copy_items "$root_dir/data/config" "$XDG_CONFIG_HOME"
copy_items "$root_dir/data/home-config" "$HOME"

if [[ "$dry" != "1" ]]; then
  ln -sf "$XDG_CONFIG_HOME/zsh/.zshenv" "$HOME/.zshenv"
fi